// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generateRegistry.ts
// Regenerate by running: pnpm run generate:registry

import type { NativeAssetConfig, TokenAssetConfig } from '../types';

import * as BitcoinExports from '../blockchains/bitcoin';
import * as AbstractEthExports from '../blockchains/evm/abstract-eth';
import * as AdiChainExports from '../blockchains/evm/adi-chain';
import * as AevoExports from '../blockchains/evm/aevo';
import * as AgungTestExports from '../blockchains/evm/agung-test';
import * as AlephZeroEvmExports from '../blockchains/evm/aleph-zero-evm';
import * as AnzUatTestExports from '../blockchains/evm/anz-uat-test';
import * as ApechainExports from '../blockchains/evm/apechain';
import * as ApechainTestExports from '../blockchains/evm/apechain-test';
import * as ApexExports from '../blockchains/evm/apex';
import * as ArbGoerliExports from '../blockchains/evm/arb-goerli';
import * as ArbSepoliaExports from '../blockchains/evm/arb-sepolia';
import * as ArbitrumExports from '../blockchains/evm/arbitrum';
import * as ArbitrumRinExports from '../blockchains/evm/arbitrum-rin';
import * as ArbitrumSepoliaExports from '../blockchains/evm/arbitrum-sepolia';
import * as ArcTestExports from '../blockchains/evm/arc-test';
import * as AstarExports from '../blockchains/evm/astar';
import * as AstarShibuyaExports from '../blockchains/evm/astar-shibuya';
import * as AstarTestExports from '../blockchains/evm/astar-test';
import * as AuroraExports from '../blockchains/evm/aurora';
import * as AvalancheExports from '../blockchains/evm/avalanche';
import * as AvalancheFujiExports from '../blockchains/evm/avalanche-fuji';
import * as AvaxtestExports from '../blockchains/evm/avaxtest';
import * as BahamutExports from '../blockchains/evm/bahamut';
import * as BaseExports from '../blockchains/evm/base';
import * as BaseSepoliaExports from '../blockchains/evm/base-sepolia';
import * as BasechainEthTest3Exports from '../blockchains/evm/basechain-eth-test3';
import * as BasechainEthTest5Exports from '../blockchains/evm/basechain-eth-test5';
import * as BerachainExports from '../blockchains/evm/berachain';
import * as BerachainArtioTestExports from '../blockchains/evm/berachain-artio-test';
import * as BerachainTestExports from '../blockchains/evm/berachain-test';
import * as BlastExports from '../blockchains/evm/blast';
import * as BnbExports from '../blockchains/evm/bnb';
import * as BnbTestnetExports from '../blockchains/evm/bnb-testnet';
import * as BobChainExports from '../blockchains/evm/bob-chain';
import * as BobChainTestExports from '../blockchains/evm/bob-chain-test';
import * as BotanixEthExports from '../blockchains/evm/botanix-eth';
import * as BotanixEthTestExports from '../blockchains/evm/botanix-eth-test';
import * as BscTestExports from '../blockchains/evm/bsc-test';
import * as CaminoExports from '../blockchains/evm/camino';
import * as CaminoColumbusExports from '../blockchains/evm/camino-columbus';
import * as CantoExports from '../blockchains/evm/canto';
import * as CantoTestnetExports from '../blockchains/evm/canto-testnet';
import * as CanvasTestExports from '../blockchains/evm/canvas-test';
import * as CbtcTestExports from '../blockchains/evm/cbtc-test';
import * as CbtcTestDeprecatedExports from '../blockchains/evm/cbtc-test-deprecated';
import * as CeloExports from '../blockchains/evm/celo';
import * as CeloAlfajoresExports from '../blockchains/evm/celo-alfajores';
import * as CeloBaklavaExports from '../blockchains/evm/celo-baklava';
import * as CentrifugeExports from '../blockchains/evm/centrifuge';
import * as CentrifugeTestExports from '../blockchains/evm/centrifuge-test';
import * as ChilizExports from '../blockchains/evm/chiliz';
import * as ChilizV2Exports from '../blockchains/evm/chiliz-v2';
import * as ChilizV2TestnetExports from '../blockchains/evm/chiliz-v2-testnet';
import * as ChzExports from '../blockchains/evm/chz';
import * as Chz2Exports from '../blockchains/evm/chz2';
import * as Chz2TestExports from '../blockchains/evm/chz2-test';
import * as CitreaExports from '../blockchains/evm/citrea';
import * as CitreaTestExports from '../blockchains/evm/citrea-test';
import * as CodexExports from '../blockchains/evm/codex';
import * as CodexTestExports from '../blockchains/evm/codex-test';
import * as ConfluxEspaceExports from '../blockchains/evm/conflux-espace';
import * as ConfluxEspaceTestExports from '../blockchains/evm/conflux-espace-test';
import * as CoreCoredaoExports from '../blockchains/evm/core-coredao';
import * as CoreCoredaoTestExports from '../blockchains/evm/core-coredao-test';
import * as CoredaoTestExports from '../blockchains/evm/coredao-test';
import * as CronosExports from '../blockchains/evm/cronos';
import * as CronosTestExports from '../blockchains/evm/cronos-test';
import * as DnbTbdTestExports from '../blockchains/evm/dnb-tbd-test';
import * as DsethDevExports from '../blockchains/evm/dseth-dev';
import * as EthNahmiiExports from '../blockchains/evm/eth-nahmii';
import * as EthTestHoodiExports from '../blockchains/evm/eth-test-hoodi';
import * as EthTest2Exports from '../blockchains/evm/eth-test2';
import * as EthTest3Exports from '../blockchains/evm/eth-test3';
import * as EthTest5Exports from '../blockchains/evm/eth-test5';
import * as EthTest6Exports from '../blockchains/evm/eth-test6';
import * as EtherealMainnetExports from '../blockchains/evm/ethereal-mainnet';
import * as EtherealTestExports from '../blockchains/evm/ethereal-test';
import * as EthereumExports from '../blockchains/evm/ethereum';
import * as EthereumClassicExports from '../blockchains/evm/ethereum-classic';
import * as EthereumHoleskyExports from '../blockchains/evm/ethereum-holesky';
import * as EthereumSepoliaExports from '../blockchains/evm/ethereum-sepolia';
import * as EthereumpowExports from '../blockchains/evm/ethereumpow';
import * as EtherlinkExports from '../blockchains/evm/etherlink';
import * as EtherlinkGy17rjTestExports from '../blockchains/evm/etherlink-gy17rj-test';
import * as EtherlinkShadownetTestExports from '../blockchains/evm/etherlink-shadownet-test';
import * as EtherlinkTestExports from '../blockchains/evm/etherlink-test';
import * as EtherlinkTestnetExports from '../blockchains/evm/etherlink-testnet';
import * as EvmosExports from '../blockchains/evm/evmos';
import * as FantomExports from '../blockchains/evm/fantom';
import * as FbInternalEthExports from '../blockchains/evm/fb-internal-eth';
import * as FilecoinExports from '../blockchains/evm/filecoin';
import * as FlareExports from '../blockchains/evm/flare';
import * as FlowChainExports from '../blockchains/evm/flow-chain';
import * as FlowChainTestExports from '../blockchains/evm/flow-chain-test';
import * as Fraxtal2yjfokExports from '../blockchains/evm/fraxtal-2yjfok';
import * as FraxtalTestnetTestExports from '../blockchains/evm/fraxtal-testnet-test';
import * as GnosisExports from '../blockchains/evm/gnosis';
import * as GnosisChiadoExports from '../blockchains/evm/gnosis-chiado';
import * as GnosisTestExports from '../blockchains/evm/gnosis-test';
import * as GunGunzillaExports from '../blockchains/evm/gun-gunzilla';
import * as GunGunzillaTestExports from '../blockchains/evm/gun-gunzilla-test';
import * as GusdtStableExports from '../blockchains/evm/gusdt-stable';
import * as GusdtTestExports from '../blockchains/evm/gusdt-test';
import * as HecoExports from '../blockchains/evm/heco';
import * as HecoTestnetExports from '../blockchains/evm/heco-testnet';
import * as HederaEvmExports from '../blockchains/evm/hedera-evm';
import * as HederaEvmTestExports from '../blockchains/evm/hedera-evm-test';
import * as HtTestExports from '../blockchains/evm/ht-test';
import * as HumanityExports from '../blockchains/evm/humanity';
import * as HumanityTestExports from '../blockchains/evm/humanity-test';
import * as HypeEthExports from '../blockchains/evm/hype-eth';
import * as HypeEthTestExports from '../blockchains/evm/hype-eth-test';
import * as ImmutableZkevmExports from '../blockchains/evm/immutable-zkevm';
import * as ImmutableZkevmTestnetExports from '../blockchains/evm/immutable-zkevm-testnet';
import * as InkEthExports from '../blockchains/evm/ink-eth';
import * as InkEthTestExports from '../blockchains/evm/ink-eth-test';
import * as IotaEvmExports from '../blockchains/evm/iota-evm';
import * as IotexExports from '../blockchains/evm/iotex';
import * as KaiaExports from '../blockchains/evm/kaia';
import * as KaiaTestnetExports from '../blockchains/evm/kaia-testnet';
import * as KatanaEthExports from '../blockchains/evm/katana-eth';
import * as KavaExports from '../blockchains/evm/kava';
import * as LachainExports from '../blockchains/evm/lachain';
import * as LineaExports from '../blockchains/evm/linea';
import * as LineaSepoliaExports from '../blockchains/evm/linea-sepolia';
import * as LineaTestnetExports from '../blockchains/evm/linea-testnet';
import * as LiskExports from '../blockchains/evm/lisk';
import * as LumiaLumiaExports from '../blockchains/evm/lumia-lumia';
import * as MantaExports from '../blockchains/evm/manta';
import * as MantleExports from '../blockchains/evm/mantle';
import * as MantleSepoliaExports from '../blockchains/evm/mantle-sepolia';
import * as MegaEthTestExports from '../blockchains/evm/mega-eth-test';
import * as MegaethMainnetExports from '../blockchains/evm/megaeth-mainnet';
import * as MetisEvmExports from '../blockchains/evm/metis-evm';
import * as MirasmandaExports from '../blockchains/evm/mirasmanda';
import * as MonadExports from '../blockchains/evm/monad';
import * as MonadTestExports from '../blockchains/evm/monad-test';
import * as MoonbeamExports from '../blockchains/evm/moonbeam';
import * as MoonriverExports from '../blockchains/evm/moonriver';
import * as MorphExports from '../blockchains/evm/morph';
import * as MorphTestExports from '../blockchains/evm/morph-test';
import * as NeroExports from '../blockchains/evm/nero';
import * as NeroTestExports from '../blockchains/evm/nero-test';
import * as OasysExports from '../blockchains/evm/oasys';
import * as OasysTestnetExports from '../blockchains/evm/oasys-testnet';
import * as OmniEvmExports from '../blockchains/evm/omni-evm';
import * as OmniEvmTestExports from '../blockchains/evm/omni-evm-test';
import * as OptSepoliaExports from '../blockchains/evm/opt-sepolia';
import * as OptimismExports from '../blockchains/evm/optimism';
import * as OptimismSepoliaExports from '../blockchains/evm/optimism-sepolia';
import * as OptimisticKovExports from '../blockchains/evm/optimistic-kov';
import * as PeaqExports from '../blockchains/evm/peaq';
import * as PlasmaExports from '../blockchains/evm/plasma';
import * as PlasmaTestExports from '../blockchains/evm/plasma-test';
import * as PlumeExports from '../blockchains/evm/plume';
import * as PlumePlumeExports from '../blockchains/evm/plume-plume';
import * as PolygonExports from '../blockchains/evm/polygon';
import * as PolygonAmoyExports from '../blockchains/evm/polygon-amoy';
import * as PolygonTestMumbaiExports from '../blockchains/evm/polygon-test-mumbai';
import * as PolygonZkevmExports from '../blockchains/evm/polygon-zkevm';
import * as PolygonZkevmTestnetExports from '../blockchains/evm/polygon-zkevm-testnet';
import * as RedbellyExports from '../blockchains/evm/redbelly';
import * as RedbellyTestnetExports from '../blockchains/evm/redbelly-testnet';
import * as RobinhoodChainTestnetTestExports from '../blockchains/evm/robinhood-chain-testnet-test';
import * as RoninExports from '../blockchains/evm/ronin';
import * as RskExports from '../blockchains/evm/rsk';
import * as RskTestExports from '../blockchains/evm/rsk-test';
import * as RskTestnetExports from '../blockchains/evm/rsk-testnet';
import * as ScrollExports from '../blockchains/evm/scroll';
import * as ScrollSepoliaExports from '../blockchains/evm/scroll-sepolia';
import * as SeiExports from '../blockchains/evm/sei';
import * as SeiTestExports from '../blockchains/evm/sei-test';
import * as SeismicTestExports from '../blockchains/evm/seismic-test';
import * as ShimmerEvmExports from '../blockchains/evm/shimmer-evm';
import * as ShimmerEvmTestnetExports from '../blockchains/evm/shimmer-evm-testnet';
import * as SmartbchExports from '../blockchains/evm/smartbch';
import * as SomniaExports from '../blockchains/evm/somnia';
import * as SomniaTestExports from '../blockchains/evm/somnia-test';
import * as SoneiumExports from '../blockchains/evm/soneium';
import * as SoneiumMinatoExports from '../blockchains/evm/soneium-minato';
import * as SongbirdExports from '../blockchains/evm/songbird';
import * as SongbirdLegacyExports from '../blockchains/evm/songbird-legacy';
import * as SonicExports from '../blockchains/evm/sonic';
import * as SonicBlazeExports from '../blockchains/evm/sonic-blaze';
import * as SonicTestnet2TestExports from '../blockchains/evm/sonic-testnet2-test';
import * as SophonExports from '../blockchains/evm/sophon';
import * as SophonTestExports from '../blockchains/evm/sophon-test';
import * as TacExports from '../blockchains/evm/tac';
import * as TelosExports from '../blockchains/evm/telos';
import * as TelosTestExports from '../blockchains/evm/telos-test';
import * as TempoExports from '../blockchains/evm/tempo';
import * as TempoModeratoTestExports from '../blockchains/evm/tempo-moderato-test';
import * as TokenizeXchangeExports from '../blockchains/evm/tokenize-xchange';
import * as TurboTestnetExports from '../blockchains/evm/turbo-testnet';
import * as UnichainEthExports from '../blockchains/evm/unichain-eth';
import * as UnichainSepoliaTestExports from '../blockchains/evm/unichain-sepolia-test';
import * as VelasExports from '../blockchains/evm/velas';
import * as VelasTestnetExports from '../blockchains/evm/velas-testnet';
import * as VictionExports from '../blockchains/evm/viction';
import * as WemixExports from '../blockchains/evm/wemix';
import * as WemixTestnetExports from '../blockchains/evm/wemix-testnet';
import * as WirexpayEthExports from '../blockchains/evm/wirexpay-eth';
import * as WmtxExports from '../blockchains/evm/wmtx';
import * as WomoxExports from '../blockchains/evm/womox';
import * as WorldchainExports from '../blockchains/evm/worldchain';
import * as WorldchainSepoliaExports from '../blockchains/evm/worldchain-sepolia';
import * as XdcExports from '../blockchains/evm/xdc';
import * as XdcApothemTestnetTestExports from '../blockchains/evm/xdc-apothem-testnet-test';
import * as ZeroGEvmExports from '../blockchains/evm/zero-g-evm';
import * as ZeroGEvmTestExports from '../blockchains/evm/zero-g-evm-test';
import * as ZilliqaExports from '../blockchains/evm/zilliqa';
import * as ZilliqaTestExports from '../blockchains/evm/zilliqa-test';
import * as ZircuitEthExports from '../blockchains/evm/zircuit-eth';
import * as ZircuitEthTestExports from '../blockchains/evm/zircuit-eth-test';
import * as ZkevmTestExports from '../blockchains/evm/zkevm-test';
import * as ZksyncEraExports from '../blockchains/evm/zksync-era';
import * as ZksyncEraGoerliExports from '../blockchains/evm/zksync-era-goerli';
import * as ZksyncEraSepoliaExports from '../blockchains/evm/zksync-era-sepolia';
import * as ZksyncEraTestExports from '../blockchains/evm/zksync-era-test';

import { ERC20_TOKENS as Avalanche_ERC20_TOKENS } from '../blockchains/evm/avalanche/tokens/erc20';
import { ERC20_TOKENS as Base_ERC20_TOKENS } from '../blockchains/evm/base/tokens/erc20';
import { ERC20_TOKENS as Bnb_ERC20_TOKENS } from '../blockchains/evm/bnb/tokens/erc20';
import { ERC20_TOKENS as Ethereum_ERC20_TOKENS } from '../blockchains/evm/ethereum/tokens/erc20';
import { ERC20_TOKENS as Flare_ERC20_TOKENS } from '../blockchains/evm/flare/tokens/erc20';
import { ERC20_TOKENS as Polygon_ERC20_TOKENS } from '../blockchains/evm/polygon/tokens/erc20';
import { ERC20_TOKENS as Songbird_ERC20_TOKENS } from '../blockchains/evm/songbird/tokens/erc20';


/**
 * All native blockchain assets
 * Auto-discovered from blockchains/ directory
 */
export const NATIVE_ASSETS: NativeAssetConfig[] = [
  BitcoinExports.BTC,
  BitcoinExports.BTC_TEST,
  AbstractEthExports.ABSTRACT_ETH,
  AdiChainExports.ADI_CHAIN,
  AevoExports.AEVO,
  AgungTestExports.AGUNG_TEST,
  AlephZeroEvmExports.ALEPH_ZERO_EVM,
  AnzUatTestExports.ANZ_UAT_TEST,
  ApechainExports.APECHAIN,
  ApechainTestExports.APECHAIN_TEST,
  ApexExports.APEX,
  ArbGoerliExports.ARB_GOERLI,
  ArbSepoliaExports.ARB_SEPOLIA,
  ArbitrumExports.ETH_AETH,
  ArbitrumRinExports.ARBITRUM_RIN,
  ArbitrumSepoliaExports.ETH_AETH_SEPOLIA,
  ArcTestExports.ARC_TEST,
  AstarExports.ASTR_ASTR,
  AstarShibuyaExports.ASTR_TEST,
  AstarTestExports.ASTAR_TEST,
  AuroraExports.AURORA_DEV,
  AvalancheExports.AVAX,
  AvalancheFujiExports.AVALANCHE_FUJI,
  AvaxtestExports.AVAXTEST,
  BahamutExports.FASTEX_BAHAMUT,
  BaseExports.BASE,
  BaseSepoliaExports.BASECHAIN_ETH_TEST5,
  BasechainEthTest3Exports.BASECHAIN_ETH_TEST3,
  BasechainEthTest5Exports.BASECHAIN_ETH_TEST5,
  BerachainExports.BERACHAIN,
  BerachainArtioTestExports.BERACHAIN_ARTIO_TEST,
  BerachainTestExports.BERACHAIN_TEST,
  BlastExports.BLAST,
  BnbExports.BNB,
  BnbTestnetExports.BNB_TEST,
  BobChainExports.BOB_CHAIN,
  BobChainTestExports.BOB_CHAIN_TEST,
  BotanixEthExports.BOTANIX_ETH,
  BotanixEthTestExports.BOTANIX_ETH_TEST,
  BscTestExports.BSC_TEST,
  CaminoExports.CAMINO,
  CaminoColumbusExports.CAMINO_COLUMBUS_TEST,
  CantoExports.CANTO,
  CantoTestnetExports.CANTO_TEST,
  CanvasTestExports.CANVAS_TEST,
  CbtcTestExports.CBTC_TEST,
  CbtcTestDeprecatedExports.cBTC_TEST_DEPRECATED,
  CeloExports.CELO,
  CeloAlfajoresExports.CELO_ALFAJORES,
  CeloBaklavaExports.CELO_BAK,
  CentrifugeExports.CENTRIFUGE,
  CentrifugeTestExports.CENTRIFUGE_TEST,
  ChilizExports.CHZ_CHZ,
  ChilizV2Exports.CHZ_CHZ2,
  ChilizV2TestnetExports.CHZ_CHZ2_TEST,
  ChzExports.CHZ,
  Chz2Exports.CHZ2,
  Chz2TestExports.CHZ2_TEST,
  CitreaExports.CITREA,
  CitreaTestExports.CITREA_TEST,
  CodexExports.CODEX,
  CodexTestExports.CODEX_TEST,
  ConfluxEspaceExports.CONFLUX_ESPACE,
  ConfluxEspaceTestExports.CONFLUX_ESPACE_TEST,
  CoreCoredaoExports.CORE_COREDAO,
  CoreCoredaoTestExports.CORE_COREDAO_TEST,
  CoredaoTestExports.COREDAO_TEST,
  CronosExports.CRONOS,
  CronosTestExports.CRONOS_TEST,
  DnbTbdTestExports.DNB_TBD_TEST,
  DsethDevExports.DSETH_DEV,
  EthNahmiiExports.ETH_NAHMII,
  EthTestHoodiExports.ETH_TEST_HOODI,
  EthTest2Exports.ETH_TEST2,
  EthTest3Exports.ETH_TEST3,
  EthTest5Exports.ETH_TEST5,
  EthTest6Exports.ETH_TEST6,
  EtherealMainnetExports.ETHEREAL_MAINNET,
  EtherealTestExports.ETHEREAL_TEST,
  EthereumExports.ETH,
  EthereumClassicExports.ETC,
  EthereumClassicExports.ETC_TEST,
  EthereumHoleskyExports.ETH_TEST6,
  EthereumSepoliaExports.ETH_TEST5,
  EthereumpowExports.ETHW,
  EtherlinkExports.ETHERLINK,
  EtherlinkGy17rjTestExports.ETHERLINK_GY17RJ_TEST,
  EtherlinkShadownetTestExports.ETHERLINK_SHADOWNET_TEST,
  EtherlinkTestExports.ETHERLINK_TEST,
  EtherlinkTestnetExports.XTZ_ETHERLINK_TEST,
  EvmosExports.EVMOS,
  FantomExports.FTM_FANTOM,
  FbInternalEthExports.FB_INTERNAL_ETH,
  FilecoinExports.FILECOIN_FEVM,
  FlareExports.FLR,
  FlowChainExports.FLOW_CHAIN,
  FlowChainTestExports.FLOW_CHAIN_TEST,
  Fraxtal2yjfokExports.FRAXTAL_2YJFOK,
  FraxtalTestnetTestExports.FRAXTAL_TESTNET_TEST,
  GnosisExports.XDAI,
  GnosisChiadoExports.XDAI_TEST,
  GnosisTestExports.GNOSIS_TEST,
  GunGunzillaExports.GUN_GUNZILLA,
  GunGunzillaTestExports.GUN_GUNZILLA_TEST,
  GusdtStableExports.GUSDT_STABLE,
  GusdtTestExports.GUSDT_TEST,
  HecoExports.HT_CHAIN,
  HecoTestnetExports.HT_CHAIN_TEST,
  HederaEvmExports.HEDERA_EVM,
  HederaEvmTestExports.HEDERA_EVM_TEST,
  HtTestExports.HT_TEST,
  HumanityExports.HUMANITY,
  HumanityTestExports.HUMANITY_TEST,
  HypeEthExports.HYPE_ETH,
  HypeEthTestExports.HYPE_ETH_TEST,
  ImmutableZkevmExports.IMX_ZKEVM,
  ImmutableZkevmTestnetExports.IMX_ZKEVM_TEST,
  InkEthExports.INK_ETH,
  InkEthTestExports.INK_ETH_TEST,
  IotaEvmExports.IOTA_EVM,
  IotexExports.IOTX_IOTEX,
  KaiaExports.KLAY_KAIA,
  KaiaTestnetExports.KLAY_KAIA_TEST,
  KatanaEthExports.KATANA_ETH,
  KavaExports.KAVA_KAVA,
  LachainExports.LACHAIN,
  LineaExports.LINEA,
  LineaSepoliaExports.LINEA_SEPOLIA_TEST,
  LineaTestnetExports.LINEA_TEST,
  LiskExports.LISK,
  LumiaLumiaExports.LUMIA_LUMIA,
  MantaExports.MANTA,
  MantleExports.MANTLE,
  MantleSepoliaExports.MANTLE_TEST,
  MegaEthTestExports.MEGA_ETH_TEST,
  MegaethMainnetExports.MEGAETH_MAINNET,
  MetisEvmExports.METIS_EVM,
  MirasmandaExports.MIRASMANDA,
  MonadExports.MONAD,
  MonadTestExports.MONAD_TEST,
  MoonbeamExports.GLMR_GLMR,
  MoonriverExports.MOVR_MOVR,
  MorphExports.MORPH,
  MorphTestExports.MORPH_TEST,
  NeroExports.NERO,
  NeroTestExports.NERO_TEST,
  OasysExports.OAS,
  OasysTestnetExports.OAS_TEST,
  OmniEvmExports.OMNI_EVM,
  OmniEvmTestExports.OMNI_EVM_TEST,
  OptSepoliaExports.OPT_SEPOLIA,
  OptimismExports.ETH_OPT,
  OptimismSepoliaExports.ETH_OPT_SEPOLIA,
  OptimisticKovExports.OPTIMISTIC_KOV,
  PeaqExports.PEAQ,
  PlasmaExports.PLASMA,
  PlasmaTestExports.PLASMA_TEST,
  PlumeExports.PLUME,
  PlumePlumeExports.PLUME_PLUME,
  PolygonExports.MATIC_POLYGON,
  PolygonAmoyExports.AMOY_POLYGON_TEST,
  PolygonTestMumbaiExports.POLYGON_TEST_MUMBAI,
  PolygonZkevmExports.ETH_ZKEVM,
  PolygonZkevmTestnetExports.ETH_ZKEVM_TEST,
  RedbellyExports.REDBELLY,
  RedbellyTestnetExports.REDBELLY_TEST,
  RobinhoodChainTestnetTestExports.ROBINHOOD_CHAIN_TESTNET_TEST,
  RoninExports.RON,
  RskExports.RBTC,
  RskTestExports.RSK_TEST,
  RskTestnetExports.RBTC_TEST,
  ScrollExports.SCROLL,
  ScrollSepoliaExports.SCROLL_SEPOLIA_TEST,
  SeiExports.SEI,
  SeiTestExports.SEI_TEST,
  SeismicTestExports.SEISMIC_TEST,
  ShimmerEvmExports.SMR_SMR,
  ShimmerEvmTestnetExports.SMR_TEST,
  SmartbchExports.SMARTBCH,
  SomniaExports.SOMNIA,
  SomniaTestExports.SOMNIA_TEST,
  SoneiumExports.ETH_SONEIUM,
  SoneiumMinatoExports.SONEIUM_MINATO_TEST,
  SongbirdExports.SGB,
  SongbirdLegacyExports.SONGBIRD_LEGACY,
  SonicExports.SONIC,
  SonicBlazeExports.SONIC_TEST,
  SonicTestnet2TestExports.SONIC_TESTNET2_TEST,
  SophonExports.SOPHON,
  SophonTestExports.SOPHON_TEST,
  TacExports.TAC,
  TelosExports.TELOS,
  TelosTestExports.TELOS_TEST,
  TempoExports.TEMPO,
  TempoModeratoTestExports.TEMPO_MODERATO_TEST,
  TokenizeXchangeExports.TKX,
  TurboTestnetExports.TURBO_TESTNET,
  UnichainEthExports.UNICHAIN_ETH,
  UnichainSepoliaTestExports.UNICHAIN_SEPOLIA_TEST,
  VelasExports.VLX_VLX,
  VelasTestnetExports.VLX_TEST,
  VictionExports.VICTION,
  WemixExports.WEMIX,
  WemixTestnetExports.WEMIX_TEST,
  WirexpayEthExports.WIREXPAY_ETH,
  WmtxExports.WMTX,
  WomoxExports.WOMOX,
  WorldchainExports.WORLDCHAIN,
  WorldchainSepoliaExports.WORLDCHAIN_TEST,
  XdcExports.XDC,
  XdcApothemTestnetTestExports.XDC_APOTHEM_TESTNET_TEST,
  ZeroGEvmExports.ZERO_G_EVM,
  ZeroGEvmTestExports.ZERO_G_EVM_TEST,
  ZilliqaExports.ZILLIQA,
  ZilliqaTestExports.ZILLIQA_TEST,
  ZircuitEthExports.ZIRCUIT_ETH,
  ZircuitEthTestExports.ZIRCUIT_ETH_TEST,
  ZkevmTestExports.ZKEVM_TEST,
  ZksyncEraExports.ETH_ZKSYNC_ERA,
  ZksyncEraGoerliExports.ETH_ZKSYNC_ERA_TEST,
  ZksyncEraSepoliaExports.ZKSYNC_ERA_SEPOLIA,
  ZksyncEraTestExports.ZKSYNC_ERA_TEST,
];

/**
 * All token assets
 * Auto-discovered from blockchains/<blockchain>/tokens/ directories
 */
export const TOKEN_ASSETS: TokenAssetConfig[] = [
  ...Avalanche_ERC20_TOKENS,
  ...Base_ERC20_TOKENS,
  ...Bnb_ERC20_TOKENS,
  ...Ethereum_ERC20_TOKENS,
  ...Flare_ERC20_TOKENS,
  ...Polygon_ERC20_TOKENS,
  ...Songbird_ERC20_TOKENS,
];
