import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function toPascalCase(str: string): string {
  return str
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

const blockchainsDir = path.join(__dirname, "../src/blockchains");

let nativeImports = "";
let nativeExports = "";
let tokenImports = "";
let tokenExports = "";
let totalChains = 0;
const seenPascalNames = new Set<string>();

function processChainDir(dir: string, relativePath: string) {
  const indexPath = path.join(blockchainsDir, relativePath, "index.ts");
  if (!fs.existsSync(indexPath)) {
    console.warn(`Skipping ${relativePath} - no index.ts found`);
    return;
  }

  totalChains++;
  const pascalCase = toPascalCase(dir);

  if (seenPascalNames.has(pascalCase)) {
    throw new Error(
      `Duplicate name "${pascalCase}" - chain dirs "${dir}" and another chain produce the same identifier. Rename one.`,
    );
  }
  seenPascalNames.add(pascalCase);

  nativeImports += `import * as ${pascalCase}Exports from '../blockchains/${relativePath}';\n`;

  const indexContent = fs.readFileSync(indexPath, "utf-8");
  const exportMatches = Array.from(
    indexContent.matchAll(/export const (\w+): NativeAssetConfig/g),
  );
  const constNames = exportMatches.length
    ? exportMatches.map((m) => m[1])
    : [pascalCase.toUpperCase()];

  for (const constName of constNames) {
    nativeExports += `  ${pascalCase}Exports.${constName},\n`;
  }

  // Check if blockchain has tokens
  const tokensDir = path.join(blockchainsDir, relativePath, "tokens");
  if (fs.existsSync(tokensDir)) {
    const tokenTypes = fs
      .readdirSync(tokensDir)
      .filter((f) => fs.statSync(path.join(tokensDir, f)).isDirectory());

    for (const tokenType of tokenTypes) {
      const tokenTypeUpper = tokenType.toUpperCase();
      const arrayName = `${tokenTypeUpper}_TOKENS`;

      tokenImports += `import { ${arrayName} as ${pascalCase}_${arrayName} } from '../blockchains/${relativePath}/tokens/${tokenType}';\n`;
      tokenExports += `  ...${pascalCase}_${arrayName},\n`;
    }
  }
}

// Scan top-level blockchains dir
const topLevelDirs = fs
  .readdirSync(blockchainsDir)
  .filter((f) => fs.statSync(path.join(blockchainsDir, f)).isDirectory());

for (const entry of topLevelDirs) {
  const entryPath = path.join(blockchainsDir, entry);
  const hasIndex = fs.existsSync(path.join(entryPath, "index.ts"));

  if (hasIndex) {
    // It's a chain directly at root (non-EVM like bitcoin, solana, etc.)
    processChainDir(entry, entry);
  }

  // Always scan subdirectories - handles category folders (evm/) and mixed
  // folders that have both their own index.ts and chain subdirs (cosmos/).
  // Only include subdirs whose index.ts exports NativeAssetConfig to avoid
  // picking up non-chain subdirs like tokens/.
  const subDirs = fs
    .readdirSync(entryPath)
    .filter((f) => {
      if (!fs.statSync(path.join(entryPath, f)).isDirectory()) return false;
      const subIndex = path.join(entryPath, f, "index.ts");
      if (!fs.existsSync(subIndex)) return false;
      return fs.readFileSync(subIndex, "utf-8").includes("NativeAssetConfig");
    });

  for (const subDir of subDirs) {
    processChainDir(subDir, `${entry}/${subDir}`);
  }
}

const generatedCode = `// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generateRegistry.ts
// Regenerate by running: pnpm run generate:registry

import type { NativeAssetConfig, TokenAssetConfig } from '../types';

${nativeImports}
${tokenImports}

/**
 * All native blockchain assets
 * Auto-discovered from blockchains/ directory
 */
export const NATIVE_ASSETS: NativeAssetConfig[] = [
${nativeExports}];

/**
 * All token assets
 * Auto-discovered from blockchains/<blockchain>/tokens/ directories
 */
export const TOKEN_ASSETS: TokenAssetConfig[] = [
${tokenExports}];
`;

const outputPath = path.join(
  __dirname,
  "../src/registry/assetsRegistry.generated.ts",
);
fs.writeFileSync(outputPath, generatedCode);
console.log(
  `✅ Generated asset registry with ${totalChains} chains at ${outputPath}`,
);
